

export const imageService = (symbol_code: string) => {
    const clearsky_day = require('../assets/weather/clearsky_day.png');
    const clearsky_night = require('../assets/weather/clearsky_night.png');
    const clearsky_polartwilight = require('../assets/weather/clearsky_polartwilight.png');
    const cloudy = require('../assets/weather/cloudy.png');
    const fair_day = require('../assets/weather/fair_day.png');
    const fair_night = require('../assets/weather/fair_night.png');
    const fair_polartwilight = require('../assets/weather/fair_polartwilight.png');
    const fog = require('../assets/weather/fog.png');
    const heavyrain = require('../assets/weather/heavyrain.png');
    const heavyrainandthunder = require('../assets/weather/heavyrainandthunder.png');
    const heavyrainshowers_day = require('../assets/weather/heavyrainshowers_day.png');
    const heavyrainshowers_night = require('../assets/weather/heavyrainshowers_night.png');
    const heavyrainshowers_polartwilight = require('../assets/weather/heavyrainshowers_polartwilight.png');
    const heavyrainshowersandthunder_day = require('../assets/weather/heavyrainshowersandthunder_day.png');
    const heavyrainshowersandthunder_night = require('../assets/weather/heavyrainshowersandthunder_night.png');
    const heavyrainshowersandthunder_polartwilight = require('../assets/weather/heavyrainshowersandthunder_polartwilight.png');
    const heavysleet = require('../assets/weather/heavysleet.png');
    const heavysleetandthunder = require('../assets/weather/heavysleetandthunder.png');
    const heavysleetshowers_day = require('../assets/weather/heavysleetshowers_day.png');
    const heavysleetshowers_night = require('../assets/weather/heavysleetshowers_night.png');
    const heavysleetshowers_polartwilight = require('../assets/weather/heavysleetshowers_polartwilight.png');
    const heavysleetshowersandthunder_day = require('../assets/weather/heavysleetshowersandthunder_day.png');
    const heavysleetshowersandthunder_night = require('../assets/weather/heavysleetshowersandthunder_night.png');
    const heavysleetshowersandthunder_polartwilight = require('../assets/weather/heavysleetshowersandthunder_polartwilight.png');
    const heavysnow = require('../assets/weather/heavysnow.png');
    const heavysnowandthunder = require('../assets/weather/heavysnowandthunder.png');
    const heavysnowshowers_day = require('../assets/weather/heavysnowshowers_day.png');
    const heavysnowshowers_night = require('../assets/weather/heavysnowshowers_night.png');
    const heavysnowshowers_polartwilight = require('../assets/weather/heavysnowshowers_polartwilight.png');
    const heavysnowshowersandthunder_day = require('../assets/weather/heavysnowshowersandthunder_day.png');
    const heavysnowshowersandthunder_night = require('../assets/weather/heavysnowshowersandthunder_night.png');
    const heavysnowshowersandthunder_polartwilight = require('../assets/weather/heavysnowshowersandthunder_polartwilight.png');
    const lightrain = require('../assets/weather/lightrain.png');
    const lightrainandthunder = require('../assets/weather/lightrainandthunder.png');
    const lightrainshowers_day = require('../assets/weather/lightrainshowers_day.png');
    const lightrainshowers_night = require('../assets/weather/lightrainshowers_night.png');
    const lightrainshowers_polartwilight = require('../assets/weather/lightrainshowers_polartwilight.png');
    const lightrainshowersandthunder_day = require('../assets/weather/lightrainshowersandthunder_day.png');
    const lightrainshowersandthunder_night = require('../assets/weather/lightrainshowersandthunder_night.png');
    const lightrainshowersandthunder_polartwilight = require('../assets/weather/lightrainshowersandthunder_polartwilight.png');
    const lightsleet = require('../assets/weather/lightsleet.png');
    const lightsleetandthunder = require('../assets/weather/lightsleetandthunder.png');
    const lightsleetshowers_day = require('../assets/weather/lightsleetshowers_day.png');
    const lightsleetshowers_night = require('../assets/weather/lightsleetshowers_night.png');
    const lightsleetshowers_polartwilight = require('../assets/weather/lightsleetshowers_polartwilight.png');
    const lightsnow = require('../assets/weather/lightsnow.png');
    const lightsnowandthunder = require('../assets/weather/lightsnowandthunder.png');
    const lightsnowshowers_day = require('../assets/weather/lightsnowshowers_day.png');
    const lightsnowshowers_night = require('../assets/weather/lightsnowshowers_night.png');
    const lightsnowshowers_polartwilight = require('../assets/weather/lightsnowshowers_polartwilight.png');
    const lightssleetshowersandthunder_day = require('../assets/weather/lightssleetshowersandthunder_day.png');
    const lightssleetshowersandthunder_night = require('../assets/weather/lightssleetshowersandthunder_night.png');
    const lightssleetshowersandthunder_polartwilight = require('../assets/weather/lightssleetshowersandthunder_polartwilight.png');
    const lightssnowshowersandthunder_day = require('../assets/weather/lightssnowshowersandthunder_day.png');
    const lightssnowshowersandthunder_night = require('../assets/weather/lightssnowshowersandthunder_night.png');
    const lightssnowshowersandthunder_polartwilight = require('../assets/weather/lightssnowshowersandthunder_polartwilight.png');
    const partlycloudy_day = require('../assets/weather/partlycloudy_day.png');
    const partlycloudy_night = require('../assets/weather/partlycloudy_night.png');
    const partlycloudy_polartwilight = require('../assets/weather/partlycloudy_polartwilight.png');
    const rain = require('../assets/weather/rain.png');
    const rainandthunder = require('../assets/weather/rainandthunder.png');
    const rainshowers_day = require('../assets/weather/rainshowers_day.png');
    const rainshowers_night = require('../assets/weather/rainshowers_night.png');
    const rainshowers_polartwilight = require('../assets/weather/rainshowers_polartwilight.png');
    const rainshowersandthunder_day = require('../assets/weather/rainshowersandthunder_day.png');
    const rainshowersandthunder_night = require('../assets/weather/rainshowersandthunder_night.png');
    const rainshowersandthunder_polartwilight = require('../assets/weather/rainshowersandthunder_polartwilight.png');
    const sleet = require('../assets/weather/sleet.png');
    const sleetandthunder = require('../assets/weather/sleetandthunder.png');
    const sleetshowers_day = require('../assets/weather/sleetshowers_day.png');
    const sleetshowers_night = require('../assets/weather/sleetshowers_night.png');
    const sleetshowers_polartwilight = require('../assets/weather/sleetshowers_polartwilight.png');
    const sleetshowersandthunder_day = require('../assets/weather/sleetshowersandthunder_day.png');
    const sleetshowersandthunder_night = require('../assets/weather/sleetshowersandthunder_night.png');
    const sleetshowersandthunder_polartwilight = require('../assets/weather/sleetshowersandthunder_polartwilight.png');
    const snow = require('../assets/weather/snow.png');
    const snowandthunder = require('../assets/weather/snowandthunder.png');
    const snowshowers_day = require('../assets/weather/snowshowers_day.png');
    const snowshowers_night = require('../assets/weather/snowshowers_night.png');
    const snowshowers_polartwilight = require('../assets/weather/snowshowers_polartwilight.png');
    const snowshowersandthunder_day = require('../assets/weather/snowshowersandthunder_day.png');
    const snowshowersandthunder_night = require('../assets/weather/snowshowersandthunder_night.png');
    const snowshowersandthunder_polartwilight = require('../assets/weather/snowshowersandthunder_polartwilight.png');

    switch (symbol_code) {
        case "clearsky_day": return clearsky_day;
        case "clearsky_night": return clearsky_night;
        case "clearsky_polartwilight": return clearsky_polartwilight;
        case "cloudy": return cloudy;
        case "fair_day": return fair_day;
        case "fair_night": return fair_night;
        case "fair_polartwilight": return fair_polartwilight;
        case "fog": return fog;
        case "heavyrain" : return heavyrain;
        case "heavyrainshowersandthunder_day": return heavyrainshowersandthunder_day;
        case "heavyrainshowersandthunder_night": return heavyrainshowersandthunder_night;
        case "heavyrainshowersandthunder_polartwilight": return heavyrainshowersandthunder_polartwilight;
        case "heavyrainshowers_day": return heavyrainshowers_day;
        case "heavyrainshowers_night": return heavyrainshowers_night;
        case "heavyrainshowers_polartwilight": return heavyrainshowers_polartwilight;
        case "heavyrainandthunder" : return heavyrainandthunder;
        case "heavysleet" : return heavysleet;
        case "heavysleetandthunder" : return heavysleetandthunder;
        case "heavysleetshowers_day" : return heavysleetshowers_day;
        case "heavysleetshowers_night" : return heavysleetshowers_night;
        case "heavysleetshowers_polartwilight" : return heavysleetshowers_polartwilight;
        case "heavysleetshowersandthunder_day" : return heavysleetshowersandthunder_day;
    case "heavysleetshowersandthunder_night" : return heavysleetshowersandthunder_night;
    case "heavysleetshowersandthunder_polartwilight" : return heavysleetshowersandthunder_polartwilight;
    case "heavysnow" : return heavysnow;
    case "heavysnowandthunder" : return heavysnowandthunder;
    case "heavysnowshowers_day"  : return heavysnowshowers_day;
    case "heavysnowshowers_night" : return heavysnowshowers_night;
    case "heavysnowshowers_polartwilight" : return heavysnowshowers_polartwilight; 
    case "heavysnowshowersandthunder_day" : return heavysnowshowersandthunder_day; 
    case "heavysnowshowersandthunder_night" : return heavysnowshowersandthunder_night;
    case "heavysnowshowersandthunder_polartwilight"  : return heavysnowshowersandthunder_polartwilight;
    case "lightrain"  : return lightrain;
    case "lightrainandthunder"  : return lightrainandthunder;
    case "lightrainshowers_day"  : return lightrainshowers_day;
    case "lightrainshowers_night"   : return lightrainshowers_night;
    case "lightrainshowers_polartwilight"   : return lightrainshowers_polartwilight;
    case "lightrainshowersandthunder_day"       : return lightrainshowersandthunder_day;
    case "lightrainshowersandthunder_night"      : return lightrainshowersandthunder_night;
    case "lightrainshowersandthunder_polartwilight"     : return lightrainshowersandthunder_polartwilight;
    case "lightsleet"   : return lightsleet;
    case "lightsleetandthunder"     : return lightsleetandthunder;
    case "lightsleetshowers_day"    : return lightsleetshowers_day;
    case "lightsleetshowers_night"  : return lightsleetshowers_night;
    case "lightsleetshowers_polartwilight"  : return lightsleetshowers_polartwilight;
    case "lightsnow"  : return lightsnow;
    case "lightsnowandthunder" : return lightsnowandthunder;
    case "lightsnowshowers_day"  : return lightsnowshowers_day;
    case "lightsnowshowers_night"  : return lightsnowshowers_night;
    case "lightsnowshowers_polartwilight" : return lightsnowshowers_polartwilight;
    case "lightssleetshowersandthunder_day"  : return lightssleetshowersandthunder_day;
    case "lightssleetshowersandthunder_night"   : return lightssleetshowersandthunder_night;
    case "lightssleetshowersandthunder_polartwilight"  : return lightssleetshowersandthunder_polartwilight;
    case "lightssnowshowersandthunder_day"  : return lightssnowshowersandthunder_day;
    case "lightssnowshowersandthunder_night" : return lightssnowshowersandthunder_night;
    case "lightssnowshowersandthunder_polartwilight" : return lightssnowshowersandthunder_polartwilight;
    case "partlycloudy_day"  : return partlycloudy_day;
    case "partlycloudy_night" : return partlycloudy_night;
    case "partlycloudy_polartwilight"  : return partlycloudy_polartwilight;
    case "rain"  : return rain;
    case "rainandthunder"  : return rainandthunder;
    case "rainshowers_day"  : return rainshowers_day;
    case "rainshowers_night"  : return rainshowers_night;
    case "rainshowers_polartwilight"  : return rainshowers_polartwilight;
    case "rainshowersandthunder_day"  : return rainshowersandthunder_day;
    case "rainshowersandthunder_night"  : return rainshowersandthunder_night;
    case "rainshowersandthunder_polartwilight"  : return rainshowersandthunder_polartwilight;
    case "sleet" : return sleet;
    case "sleetandthunder" : return sleetandthunder;
    case "sleetshowers_day" : return sleetshowers_day;
    case "sleetshowers_night" : return sleetshowers_night;
    case "sleetshowers_polartwilight"  : return sleetshowers_polartwilight;
    case "sleetshowersandthunder_day"  : return sleetshowersandthunder_day;
    case "sleetshowersandthunder_night"  : return sleetshowersandthunder_night;
    case "sleetshowersandthunder_polartwilight"  : return sleetshowersandthunder_polartwilight;
    case "snow"  : return snow;
    case "snowandthunder"  : return snowandthunder;
    case "snowshowers_day"  : return snowshowers_day;
    case "snowshowers_night"  : return snowshowers_night;
    case "snowshowers_polartwilight"  : return snowshowers_polartwilight;
    case "snowshowersandthunder_day" : return snowshowersandthunder_day; 
    case "snowshowersandthunder_night" : return snowshowersandthunder_night; 
    case "snowshowersandthunder_polartwilight" : return snowshowersandthunder_polartwilight;
    default : return clearsky_day;
    }
}
